name: driver_app
description: "A new Flutter project for the driver mission dashboard."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.1.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

geolocator: ^13.0.0.
