// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0GIrsVkHG9ONsit68iLyeDt9OJx0M9o',
    appId: '1:547259836004:web:06a489a99f2ea12b876171',
    messagingSenderId: '547259836004',
    projectId: 'pulseroute-gsc',
    authDomain: 'pulseroute-gsc.firebaseapp.com',
    storageBucket: 'pulseroute-gsc.firebasestorage.app',
    measurementId: 'G-S69Z0T11P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaNlcflzdauuh_1c3IqcArTmqbMMYIBU',
    appId: '1:547259836004:android:1ad14a24e275486a876171',
    messagingSenderId: '547259836004',
    projectId: 'pulseroute-gsc',
    storageBucket: 'pulseroute-gsc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SSv8Lb1IG_Rw-4COZ6LgUTRvmEy35hA',
    appId: '1:547259836004:ios:c43aa75e982aa679876171',
    messagingSenderId: '547259836004',
    projectId: 'pulseroute-gsc',
    storageBucket: 'pulseroute-gsc.firebasestorage.app',
    iosBundleId: 'com.rvce.pulseroute',
  );
}
